import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";
import MainLayout from "./MainLayout";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    
    >
   <head>

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<link href="https://fonts.googleapis.com/css2?family=Lustria&family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet"></link>

   </head>


      <body className="bg-[#FFF9E6]">
         <MainLayout>
         <Header />
        {children}
         <Footer />
         </MainLayout>
        
        


      </body>
    </html>
  );
}
